//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoShark.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrder
    {
        public int Id { get; set; }
        public int SymbolId { get; set; }
        public long OrderId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal StopLossPrice { get; set; }
        public Nullable<System.DateTime> StopLossAt { get; set; }
        public Nullable<decimal> StopLossExecutedPrice { get; set; }
        public string Status { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Symbol Symbol { get; set; }
    }
}
